// Northern Israel cities for property location selection
export const cityOptions = [
  { value: 'נוף הגליל', label: 'נוף הגליל' },
  { value: 'נצרת', label: 'נצרת' },
  { value: 'ריינה', label: 'ריינה' },
  { value: 'יפיע', label: 'יפיע' },
  { value: 'כפרכנא', label: 'כפרכנא' },
  { value: 'כפרמנדא', label: 'כפרמנדא' },
  { value: 'אכסאל', label: 'אכסאל' },
  { value: 'חיפה', label: 'חיפה' },
  { value: 'נהריה', label: 'נהריה' },
  { value: 'עכו', label: 'עכו' },
  { value: 'צפת', label: 'צפת' },
  { value: 'טבריה', label: 'טבריה' },
  { value: 'כרמיאל', label: 'כרמיאל' },
  { value: 'מעלות-תרשיחא', label: 'מעלות-תרשיחא' },
  { value: 'קריית שמונה', label: 'קריית שמונה' },
  { value: 'בית שאן', label: 'בית שאן' },
  { value: 'מגדל העמק', label: 'מגדל העמק' },
  { value: 'עפולה', label: 'עפולה' },
  { value: 'שלומי', label: 'שלומי' },
  { value: 'מטולה', label: 'מטולה' },
  { value: 'דן', label: 'דן' },
  { value: 'קצרין', label: 'קצרין' },
  { value: 'חצור הגלילית', label: 'חצור הגלילית' },
  { value: 'כפר תבור', label: 'כפר תבור' },
  { value: 'מזרע', label: 'מזרע' },
  { value: 'יסוד המעלה', label: 'יסוד המעלה' },
  { value: 'ראש פינה', label: 'ראש פינה' },
  { value: 'כפר גלעדי', label: 'כפר גלעדי' },
  { value: 'תל חי', label: 'תל חי' },
  { value: 'מירון', label: 'מירון' },
  { value: 'פקיעין', label: 'פקיעין' },
  { value: 'סכנין', label: 'סכנין' },
  { value: 'שפרעם', label: 'שפרעם' },
  { value: 'כפר יאסיף', label: 'כפר יאסיף' },
  { value: 'ג\'ולס', label: 'ג\'ולס' },
  { value: 'מי עמי', label: 'מי עמי' },
  { value: 'אבן יהודה', label: 'אבן יהודה' },
  { value: 'זכרון יעקב', label: 'זכרון יעקב' },
  { value: 'בנימינה', label: 'בנימינה' },
  { value: 'פרדס חנה-כרכור', label: 'פרדס חנה-כרכור' },
  { value: 'קיסריה', label: 'קיסריה' },
  { value: 'רמת השרון', label: 'רמת השרון' },
  { value: 'הרצליה', label: 'הרצליה' }
]; 