// Reusable country options (Hebrew labels)
export const countryOptions = [
  { value: 'ישראל', label: 'ישראל' },
  { value: 'ארצות הברית', label: 'ארצות הברית' },
  { value: 'קנדה', label: 'קנדה' },
  { value: 'מקסיקו', label: 'מקסיקו' },
  { value: 'בריטניה', label: 'בריטניה' },
  { value: 'אירלנד', label: 'אירלנד' },
  { value: 'צרפת', label: 'צרפת' },
  { value: 'גרמניה', label: 'גרמניה' },
  { value: 'איטליה', label: 'איטליה' },
  { value: 'ספרד', label: 'ספרד' },
  { value: 'פורטוגל', label: 'פורטוגל' },
  { value: 'יוון', label: 'יוון' },
  { value: 'קפריסין', label: 'קפריסין' },
  { value: 'טורקיה', label: 'טורקיה' },
  { value: 'רומניה', label: 'רומניה' },
  { value: 'בולגריה', label: 'בולגריה' },
  { value: 'הונגריה', label: 'הונגריה' },
  { value: 'פולין', label: 'פולין' },
  { value: 'צ׳כיה', label: 'צ׳כיה' },
  { value: 'סלובקיה', label: 'סלובקיה' },
  { value: 'אוקראינה', label: 'אוקראינה' },
  { value: 'גיאורגיה', label: 'גיאורגיה' },
  { value: 'קרואטיה', label: 'קרואטיה' },
  { value: 'סרביה', label: 'סרביה' },
  { value: 'מונטנגרו', label: 'מונטנגרו' },
  { value: 'הולנד', label: 'הולנד' },
  { value: 'בלגיה', label: 'בלגיה' },
  { value: 'שווייץ', label: 'שווייץ' },
  { value: 'אוסטריה', label: 'אוסטריה' },
  { value: 'דנמרק', label: 'דנמרק' },
  { value: 'שוודיה', label: 'שוודיה' },
  { value: 'נורווגיה', label: 'נורווגיה' },
  { value: 'פינלנד', label: 'פינלנד' },
  { value: 'איחוד האמירויות', label: 'איחוד האמירויות' },
  { value: 'סעודיה', label: 'סעודיה' },
  { value: 'ירדן', label: 'ירדן' },
  { value: 'מצרים', label: 'מצרים' },
  { value: 'מרוקו', label: 'מרוקו' },
  { value: 'תוניסיה', label: 'תוניסיה' },
  { value: 'דרום אפריקה', label: 'דרום אפריקה' },
  { value: 'אוסטרליה', label: 'אוסטרליה' },
  { value: 'ניו זילנד', label: 'ניו זילנד' },
  { value: 'יפן', label: 'יפן' },
  { value: 'סין', label: 'סין' },
  { value: 'הודו', label: 'הודו' },
  { value: 'סינגפור', label: 'סינגפור' }
];

